# Generated by Django 3.0 on 2019-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[(
                'WITH', 'Withdrawal'), ('DEPS', 'Deposit')], default='WITH', max_length=4),
            preserve_default=False,
        ),
    ]
